### ISSUE TITLE
Could it be used for big data processing?

### ISSUE THREAD

**Issue by yingfeng** [apache/teaclave-sgx-sdk#10]
Since enclave page cache memory is limited to only 128MB, pages have to be evicted from trusted area to untrusted memory, which leads to frequent memory swapping if there are lots of data to be accessed, say from big data ecosystems. So how to deal with such situation? In your upcoming [qcon session](https://2018.qconbeijing.com/presentation/399), it seems some typical big data tasks as machine learning have been used together with SGX, have you suffered from the performance issue due to memory swapping?

**Comment by dingelish** [comment]
Yes I have.

In iDash'17 competition, the champion from CEA optimized the problem by using a well-designed problem-specific compression to reduce the size. They compressed the 30GB of data to 8MB and ran analysis in SGX enclave easily within tens of seconds. They used Rust-SGX-SDK to implement everything.

To achieve better performance, it is not a good option to simply re-use existing big data processing algorithm in SGX environment, due to the limitation of SGXv1. Those algorithms always consume lots of memory for speeding up and that contradicts with SGX's model. If you want to achieve best performance, please carefully redesign the algorithm by compressing the data and follow the guidelines from the CEA team.

For proof-of-concept, or simply porting existing solutions to Intel SGX environment, performance is not guaranteed, due to the SGX's limitation.

**Comment by yingfeng** [comment]
For example, I want to run a deep learning task, say ImageNet which requires nearly 200GB image files together with around 100 epochs each of which iterates all images, does there exist some guidlines to have such tasks affected as less as possible?  @dingelish  Thank you~

**Comment by dingelish** [comment]
As far as I know, there is no such guidelines.

First, you need to clarify the adversary model. Are you considering about data privacy, or only the model privacy?

If you worry about data privacy, there are two different scenarios:
1) are you running the SGX enclave on safe local machine? which means that the data itself on your hard drive is safe.
2) are you running the SGX enclave on remote server? which means that the data cannot be stored on remote server in plain text.

For (1), you can simply load files into untrusted memory and use SGX enclave to read image from untrusted memory. This is because the assumption here is that the attacker cannot touch the data under any circumstances.

For (2), you can implement something like a 'encrypted file system'  using symmetric crypto and expose interface to the enclave. And you can pass the key to the enclave via secure channel, established by remote attestation. On each access to an image, the enclave could make ocall to the fs interface and fetch a file and decrypt it. Here you need to solve the side channel problem -- the attacker could monitor I/O outputs and may know which file your enclave is accessing.

If you only worries about model privacy, it's trivial.

I recommend you reconsider the adversary model in the SGX+AI research. The ability of attacker impacts the solution significantly.

**Comment by yingfeng** [comment]
The latter situation for data privacy is just what I wanted.  In that case, given your suggestion, it seems the 128MB memory issue does not appear since only the  symmetric crypto is required by the application running within encave, have I misunderstood?

**Comment by dingelish** [comment]
You are correct.

Before decrypting anything, the enclave should copy it into the sgx enclave. Then the enclave decrypt it inside the enclave.

What I want to say is that this solution always suffers from side channel attacks -- the attacker could get many information about which part of data is being used inside the enclave.

**Comment by yingfeng** [comment]
Got it, thank you. What you've mentioned the side channel attack is really the key issue to whether such model could be practical.
