### ISSUE TITLE
update third-party wasmi=0.4.3

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#112]
I would wish to see upstream support for sgx in wasmi (and I think something's happening as I see @elichai committing ;-)

What's the road forward? I would need wasmi >=0.4.3. 

Currently I'm working with the upstream version and it does build. But I get `core dumped`:
https://github.com/paritytech/wasmi/issues/182

I'd be happy to help updating third-party/wasmi, but I guess the better way would be filing upstream PR's to fix their version...

**Comment by dingelish** [comment]
let me get it upgraded :-)

**Comment by dingelish** [comment]
Do you prefer the most recent 0.4.5, or just 0.4.3?

**Comment by dingelish** [comment]
Finished the first stage: port parity-wasm
https://github.com/mesalock-linux/parity-wasm-sgx

I setup auto pull to keep it updated with `paritytech:master` and nightly build + tests to test if it works with latest codes and rust-sgx-sdk.

Will do the same on wasmi

**Comment by dingelish** [comment]
Seems that v0.31.3(b585340efbf84667823b69e91f9f5eacc60a720f) is the exact one of parity-wasm. I'll add a branch for this version.

**Comment by dingelish** [comment]
v0.31.3 branch has been added to parity-wasm-sgx.

https://github.com/mesalock-linux/wasmi-sgx
I forked the wasmi here and the validation sub-crate seems working fine.

Will port wasmi tomorrow.

**Comment by brenzi** [comment]
I think wasmi=0.4.3 would be good as it is the latest official release.
MASTER includes fixes that made my sgx build work with upstream (though I get core dumped as reported above), but I guess if you're porting wasmi=0.4.3 for sgx, you'll fix the remaining issues anyway).

**Comment by dingelish** [comment]
https://github.com/mesalock-linux/wasmi-sgx

I think it's good to go. It can [pass](http://ci.mesalock-linux.org/mesalock-linux/wasmi-sgx/13) all built-in `#[test]`s now. And it has been setup with Pull to keep update with paritytech/wasmi.

I added a [patch](https://github.com/mesalock-linux/wasmi-sgx/blob/master/sgx/wasmi-sgx-test/make_pub.diff) to make some of its `mod`s visible to the enclave. I think you guys won't needed it.

**Comment by dingelish** [comment]
Seems the ported [wasmi-sgx](https://github.com/mesalock-linux/wasmi-sgx) can pass all `#[test]`s now!

[CI record here](http://ci.mesalock-linux.org/mesalock-linux/wasmi-sgx/14)

Btw: wabt cannot 100% work in SGX because it links to the compiler. I removed everything except for essential data structure definitions and put it in `wabt-sgx` branch `v0.6.0-core` at
https://github.com/mesalock-linux/wabt-rs-sgx/commits/v0.6.0-core

To run those tests, I have to invoke the compile functions. This is solved by an OCALL function at
https://github.com/mesalock-linux/wasmi-sgx/blob/master/sgx/wasmi-sgx-test/app/src/main.rs#L155

To test everything, I add a patch
https://github.com/mesalock-linux/wasmi-sgx/blob/master/sgx/wasmi-sgx-test/make_pub.diff
to make something visible to the external enclave. Perhaps you don't need it.

**Comment by brenzi** [comment]
Thanks a lot! I'll check this out.

However, I now have a working enclave build against wasmi 5be300c99f81603f0e845443800418323d9b073a invoking a `wasm` file.

I'll check what you did to find the differences.
