### ISSUE TITLE
Migrate to SDK 2.6 Release

### ISSUE THREAD

**Issue by tomtau** [apache/teaclave-sgx-sdk#141]
https://github.com/intel/linux-sgx/commit/c505e6129a8c95852045e5ec8b08b1b230a8952a

**Comment by dingelish** [comment]
Update:

We've partially finished the upgrade. The biggest problem to solve is the change of libunwind of Intel SGX SDK. In 2.5, `GetIpInfo` is included in libtcxx and we always link to both libsgx_tstdc and libsgx_tcxx. But in 2.6, it is removed from tcxx. So in the next release, sgx_tstd will include libunwind and we'll not link to libtcxx anymore.

**Comment by dingelish** [comment]
I plan to push v1.0.9-preview to a new branch tomorrow or the day after tomorrow. It contains some breaking changes due to the offset of [`thread_policy`](https://github.com/intel/linux-sgx/blame/34421657a370c00a1a55fbf8ee29b2a1a07663e8/common/inc/internal/global_data.h#L55) has been changed. And some EDL functions are renamed. And rust-toolchain would be nightly-2019-08-01.

**Comment by tomtau** [comment]
done
