### ISSUE TITLE
v1.1.2: undefined reference to `t_signal_handler_ecall` when linking to untrusted code

### ISSUE THREAD

**Issue by assafmo** [apache/teaclave-sgx-sdk#234]
Hi :wave:

We are trying to upgrade from v1.1.1 to v1.1.2.
When building the untrusted code as a `.so` and trying to link another executable against this `.so` we get `undefined reference to 't_signal_handler_ecall'`.
When reverting the untrusted code to v1.1.1 and keeping the trusted code with v1.1.2 everything works fine.

What are we missing? :pray: 

cc @toml01 @reuvenpo @cashmaney

**Comment by mssun** [comment]
This is caused by an ecall in `sgx_urts`: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/sgx_urts/src/signal.rs#L35.

@volcano0dr and I are working on a fix.

To fix it, you can include the "sgx_signal.edl" and `extern use` the sgx_signal crate. However, this is a temporary workaround. We should fix it.

**Comment by dingelish** [comment]
I think this can be close by #235
