### ISSUE TITLE
Why TrapKind::Host is commented out?

### ISSUE THREAD

**Issue by moriaab** [apache/teaclave-sgx-sdk#32]
Hello,

why this line is commented out https://github.com/baidu/rust-sgx-sdk/blob/master/third_party/wasmi/src/lib.rs#L232?

**Comment by dingelish** [comment]
Months ago when I was porting `wasmi` I ran into a problem with serialization of `HostError`. It alert me that if an enclave could say 'Hey, you make me an HostError instead of Interpreter Error' because it may leaks something. So I chose to comment it out.

I would like to say that it's a personal decision based on my understanding of SGX security model.

But I could implement `HostError` if it's highly desired...

**Comment by moriaab** [comment]
Thank you very much. No need to implement, just being curious.
