### ISSUE TITLE
What the hack? 

### ISSUE THREAD

**Issue by daviddao** [apache/teaclave-sgx-sdk#6]
### What the hack? :rocket:

https://github.com/baidu/rust-sgx-sdk/blob/340243b138f234facfc98f561991d2e6325dd62a/dockerfile/Dockerfile#L62-L63

- Why does that work? 
- And which file do we need to delete for newer Rust versions (nightly)?

**Comment by dingelish** [comment]
- If not removing the rlib, rustc would be puzzled to link with two similar liblibc rlibs. Removing the incorrect one would resolve this problem.
- Check the size of the only two liblibc*.rlib, remove the bigger one.

**This hack will be deprecated because in the next release (maybe next week), we will resolve this linking problem perfectly.**

**Comment by daviddao** [comment]
Thanks for the quick response! Looking forward to the release! (Great work btw 🏆 )
